### ISSUE TITLE
Install fails on Synology NAS

### ISSUE THREAD

**Issue by clemouk** [mscdex/node-mariasql#111]
I've tried to install this package on my NAS drive, but it seems to fail towards the end

**Comment by mscdex** [comment]
Well, that log doesn't really say anything. Do you have the required build tools installed (e.g. gcc, g++, make, python 2.6+)?

**Comment by Eusebiotrigo** [comment]
In my Syno box it says:
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/volume1/@appstore/Node.js/usr/lib/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/volume1/@appstore/Node.js/usr/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /volume1/@appstore/Node.js/usr/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
gyp ERR! System Linux 2.6.32.12
gyp ERR! command "node" "/volume1/@appstore/Node.js/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/easyRTC/node_modules/mariasql
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

The problem is with that we do not have make or build-essentials, nothing to do with mariasql.

**Comment by mscdex** [comment]
This seems like a common problem with Synology judging by google results. So my guess is it has something to do with the build environment that they provide. Perhaps `make` is too old or something? I know node itself require (gnu) Make 3.81+ for example.

**Comment by mscdex** [comment]
You might also check the version of Python that's installed. 2.7.x is what I typically use.
