### ISSUE TITLE
Can't connect to local MySQL server through socket '/tmp/mysql.sock'

### ISSUE THREAD

**Issue by holymoly** [mscdex/node-mariasql#112]
Hi,

I've upgraded to "mariasql": "^0.2.1", and Node 4.1.2.
Before I used "mariasql": "^0.1.24", and Node 0.12.

With the old version I could connect to the remote server. With the new version I'm getting: 
```
Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2 "No such file or directory")
    at Error (native)
    at /Git/maria-backend/node_modules/mariasql/lib/Client.js:132:22
    at doNTCallback3 (node.js:441:9)
    at process._tickDomainCallback (node.js:388:17)
```
But the server is not running locally, its on a remote Machine.

My Server config is: 
```
{
  "host": "192.168.123.123",
  "user": "foo",
  "password": "bar",
  "db": "myDb",
  "multiStatements": true,
  "compress": true
}
```
Thanks in advance

**Comment by holymoly** [comment]
I did some debugging. First my code where I execute the query:
```
function queryMaria(queryString,options, cb){
  console.log('query');
  var c = new Client();
  // Preparing the query
  var pq = c.prepare(queryString);
  // console.log(queryString);
  logger.info(pq(options));
  // Array which will store the rows
  var result = [];
  var qcnt = 0;
  // Executing the query and passing parameters
  c.query(pq(options))
    .on('result', function(res) {
      // Count numbers of results
      logger.info('Result No: ' + ++qcnt);
      res.on('row', function(row) {
        result.push(row);
        logger.info('Result row: ' + inspect(row));
      })
      .on('error', function(err) {
        cb(err,null);
        logger.error('Result error: ' + inspect(err) + '  \r\n on query: ' + pq(options));
      })
      .on('end', function(info) {
        logger.info('Result finished successfully');
      });
    })
    .on('end', function() {
      // ToDo: Check if result was executed, If not nothing was found,inserted
      // updated or deleted
      cb(null, result);
      logger.info('Done with all results');
      c.end();
    });
    // Events the client listens on
    c.on('connect', function() {
        logger.info('Client connected');
      })
      .on('error', function(err) {
        logger.error('Client error: ' + err);
        cb(err,null);
      })
      .on('close', function(hadError) {
        logger.info('Client closed');
      });
    // After event listeners are setup, connect to mariadb
    // mariadbConfig should look like:
    //    {
    //      "host": "127.0.0.1",
    //      "user": "username",
    //      "password": "secret",
    //      "db": "nameOfDb",
    //      "multiStatements": true,
    //      "compress": true
    //    }
    //console.log(mariadbConfig);
    console.log('connect');
    c.connect(mariadbConfig);
};
```
Then I added these conole.log() to the lib/client.js:
```
Client.prototype.connect = function(config, cb) {
  console.log('prototype.connect');
  console.log(config);
  ...
```

The output is:
```
query
prototype.connect
undefined
connect
prototype.connect
{ host: '192.168.123.37',
  user: 'holymoly',
  password: 'gtstsdh',
  db: 'zeiterfassung',
  multiStatements: true,
  compress: true }
Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2 "No such file or directory")
    at Error (native)
    at /Git/maria-backend/node_modules/mariasql/lib/Client.js:135:22
    at doNTCallback3 (node.js:441:9)
    at process._tickDomainCallback (node.js:388:17)
[1]    75951 segmentation fault  node app.js
```

So when I call "c.connect(mariadbConfig)" once the "Client.prototype.connect = function(config, cb)" gets executed twice. And the first time the config I passed is undefined, the second time is ok.
So on the first time it will never see an IP. 
Do you have an Idea why this is called twice?

**Comment by holymoly** [comment]
Seems like an asynchronous hick up on my side. After moving c.connect(mariadbConfig) before c.query(pq(options)) it lokks better.

**Comment by mscdex** [comment]
With v0.2, `.query()` triggers an implicit connect and if you do not pass a connection config object to the constructor, then defaults are used. On *nix, the `host` would be blank, which by default means that a unix socket file is tried.

That may seem a bit unexpected, but it's the way the mysql client works. I will add a config option that allows explicitly setting `MYSQL_OPT_PROTOCOL`.

**Comment by holymoly** [comment]
Good to know. Thanks for clearing that up.
