### ISSUE TITLE
Get Error :   /node_modules/mariasql/lib/Client.js:34   on OSX

### ISSUE THREAD

**Issue by jeenhyung** [mscdex/node-mariasql#117]
server spec:
OSX 10.10.5
nginx : Ver 1.8.0
mariadb : Ver 15.1 Distrib 10.0.21-MariaDB, for osx10.10 (x86_64) using readline 5.1

I try to run my node server.
but I got a error.. that's below:

# node app.js

/../nodetServer/node_modules/mariasql/lib/Client.js:34
  this._handle = new binding({
                 ^
TypeError: undefined is not a function
    at new Client (/../nodetServer/node_modules/mariasql/lib/Client.js:34:18)
    at Object.<anonymous> (/../nodetServer/app.js:40:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

[source code] app.js

var mariasql = require('mariasql');  
global.m_sql = new mariasql( {      // line 40
  host: 'localhost',
  user: 'root',
  password: '123',
  db: 'test_db'
});

I want to solution..

**Comment by mscdex** [comment]
What version of node did you use to install? Also what compiler and compiler version are you using?
