### ISSUE TITLE
Error: Cannot find module '../build/Debug/sqlclient'

### ISSUE THREAD

**Issue by patherk** [mscdex/node-mariasql#126]
Installed latest fine on my mac, but having issues on my centos vps

node v0.10.36
npm 2.14.7

In directory did the standard 
npm install mariasql

node index.js
```
module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Debug/sqlclient'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/test/test-api/node_modules/mariasql/lib/Client.js:13:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Install

```
npm install mariasql --save
npm WARN package.json test-api@1.0.0 No description
npm WARN package.json test-api@1.0.0 No repository field.
npm WARN package.json test-api@1.0.0 No README data
npm WARN package.json test-api@1.0.0 No license field.
\
> mariasql@0.2.5 install /test/test-api/node_modules/mariasql
> node-gyp rebuild

make: Entering directory `/test/test-api/node_modules/mariasql/build'
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/aes.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/aestables.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/algebra.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/arc4.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/asn.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/bftables.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/blowfish.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/coding.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/des.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/dh.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/dsa.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/file.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/hash.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/hc128.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/integer.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/md2.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/md4.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/md5.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/misc.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/rabbit.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/random.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/ripemd.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/rsa.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/sha.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/tftables.o
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/twofish.o
  AR(target) Release/obj.target/deps/libmariadbclient/extra/yassl/taocrypt/taocrypt.a
  COPY Release/taocrypt.a
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/buffer.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/cert_wrapper.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/crypto_wrapper.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/handshake.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/lock.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/log.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/socket_wrapper.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/ssl.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/timer.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/yassl_error.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/yassl_imp.o
  CXX(target) Release/obj.target/yassl/deps/libmariadbclient/extra/yassl/src/yassl_int.o
  AR(target) Release/obj.target/deps/libmariadbclient/extra/yassl/yassl.a
  COPY Release/yassl.a
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql-common/client.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql-common/client_plugin.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql-common/mysql_async.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql-common/my_time.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql-common/pack.o
  CXX(target) Release/obj.target/clientlib/deps/libmariadbclient/sql/net_serv.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/sql/password.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/libmysql/errmsg.o
  CC(target) Release/obj.target/clientlib/deps/libmariadbclient/libmysql/libmysql.o
  AR(target) Release/obj.target/deps/libmariadbclient/libmysql/clientlib.a
  COPY Release/clientlib.a
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/array.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/charset-def.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/charset.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/errors.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/hash.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/list.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_arr_appstr.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_dirname.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_fn_ext.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_format.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_loadpath.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_pack.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_path.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_qsort.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_unixpath.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mf_wcomp.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/mulalloc.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_access.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_alloc.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_compress.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_context.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_default.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_div.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_error.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_fopen.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_fstream.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_getsystime.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_getwd.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_init.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_lib.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_malloc.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_mess.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_once.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_open.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_pthread.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_read.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_seek.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_static.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_symlink.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_thr_init.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_write.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/safemalloc.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/string.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/thr_mutex.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/typelib.o
  CC(target) Release/obj.target/mysys/deps/libmariadbclient/mysys/my_sync.o
  AR(target) Release/obj.target/deps/libmariadbclient/mysys/mysys.a
  COPY Release/mysys.a
  CXX(target) Release/obj.target/mysys_ssl/deps/libmariadbclient/mysys_ssl/my_aes.o
  CXX(target) Release/obj.target/mysys_ssl/deps/libmariadbclient/mysys_ssl/my_md5.o
  CXX(target) Release/obj.target/mysys_ssl/deps/libmariadbclient/mysys_ssl/my_rnd.o
  CXX(target) Release/obj.target/mysys_ssl/deps/libmariadbclient/mysys_ssl/my_sha1.o
  CXX(target) Release/obj.target/mysys_ssl/deps/libmariadbclient/mysys_ssl/my_sha2.o
  AR(target) Release/obj.target/deps/libmariadbclient/mysys_ssl/mysys_ssl.a
  COPY Release/mysys_ssl.a
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/bchange.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/bmove_upp.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-big5.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-bin.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-cp932.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-czech.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-eucjpms.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-euc_kr.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-extra.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-gb2312.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-gbk.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-latin1.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-mb.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-simple.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-sjis.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-tis620.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-uca.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-ucs2.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-ujis.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-utf8.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype-win1250ch.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/ctype.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/dtoa.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/int2str.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/is_prefix.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/llstr.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/longlong2str.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/my_strtoll10.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/my_vsnprintf.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/str2int.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strcend.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strcont.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strend.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strfill.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strmake.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strmov.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strmov_overlapp.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strnmov.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strxmov.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strxnmov.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/str_alloc.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/xml.o
  CC(target) Release/obj.target/strings/deps/libmariadbclient/strings/strnlen.o
  AR(target) Release/obj.target/deps/libmariadbclient/strings/strings.a
  COPY Release/strings.a
  CC(target) Release/obj.target/vio/deps/libmariadbclient/vio/vio.o
../deps/libmariadbclient/vio/vio.c: In function ‘vio_end’:
../deps/libmariadbclient/vio/vio.c:389:3: warning: implicit declaration of function ‘yaSSL_CleanUp’ [-Wimplicit-function-declaration]
   yaSSL_CleanUp();
   ^
  CC(target) Release/obj.target/vio/deps/libmariadbclient/vio/viopipe.o
  CC(target) Release/obj.target/vio/deps/libmariadbclient/vio/vioshm.o
  CC(target) Release/obj.target/vio/deps/libmariadbclient/vio/viosocket.o
  CC(target) Release/obj.target/vio/deps/libmariadbclient/vio/viossl.o
  CC(target) Release/obj.target/vio/deps/libmariadbclient/vio/viosslfactories.o
  AR(target) Release/obj.target/deps/libmariadbclient/vio/vio.a
  COPY Release/vio.a
  CC(target) Release/obj.target/zlib/deps/libmariadbclient/zlib/adler32.o
  CC(target) Release/obj.target/zlib/deps/libmariadbclient/zlib/compress.o
  CC(target) Release/obj.target/zlib/deps/libmariadbclient/zlib/crc32.o
  CC(target) Release/obj.target/zlib/deps/libmariadbclient/zlib/deflate.o
  CC(target) Release/obj.target/zlib/deps/libmariadbclient/zlib/gzclose.o
  CC(target) Release/obj.target/zlib/deps/libmariadbclient/zlib/gzlib.o
  CC(target) Release/obj.target/zlib/deps/libmariadbclient/zlib/gzread.o
  CC(target) Release/obj.target/zlib/deps/libmariadbclient/zlib/gzwrite.o
  CC(target) Release/obj.target/zlib/deps/libmariadbclient/zlib/infback.o
  CC(target) Release/obj.target/zlib/deps/libmariadbclient/zlib/inffast.o
  CC(target) Release/obj.target/zlib/deps/libmariadbclient/zlib/inflate.o
  CC(target) Release/obj.target/zlib/deps/libmariadbclient/zlib/inftrees.o
  CC(target) Release/obj.target/zlib/deps/libmariadbclient/zlib/trees.o
  CC(target) Release/obj.target/zlib/deps/libmariadbclient/zlib/uncompr.o
  CC(target) Release/obj.target/zlib/deps/libmariadbclient/zlib/zutil.o
  AR(target) Release/obj.target/deps/libmariadbclient/zlib/zlib.a
  COPY Release/zlib.a
  CXX(target) Release/obj.target/sqlclient/src/binding.o
../src/binding.cc: In member function ‘void Client::on_resultend()’:
../src/binding.cc:1223:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (r <= 0 || r >= sizeof(u64_buf))
                                        ^
../src/binding.cc:1232:42: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (r <= 0 || r >= sizeof(u64_buf))
                                          ^
../src/binding.cc:1239:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (r <= 0 || r >= sizeof(u64_buf))
                                        ^
../src/binding.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Client::LastInsertId(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cc:1534:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (r <= 0 || r >= sizeof(u64_buf))
                                        ^
  SOLINK_MODULE(target) Release/obj.target/sqlclient.node
  COPY Release/sqlclient.node
make: Leaving directory `/test/test-api/node_modules/mariasql/build'
mariasql@0.2.5 node_modules/mariasql
├── lru-cache@2.7.3
└── nan@2.1.0
```

**Comment by mscdex** [comment]
It built and installed just fine. What happens if you edit `./node_modules/mariasql/lib/Client.js` and change lines 9-14 to instead be:

```javascript
var addon = require('../build/Release/sqlclient');
```

What error does it show then?

**Comment by patherk** [comment]
Okay so made this change
```
var LRU = require('lru-cache');

var addon = require('../build/Release/sqlclient');
try {
  addon = require('../build/Release/sqlclient');
} catch (ex) {
  addon = require('../build/Debug/sqlclient');
}

var binding = addon.ClientBinding;
```

then I receive

```
node index.js

module.js:340
    throw err;
          ^
Error: Cannot find module '/test/test-api/node_modules/mariasql/lib/index.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by mscdex** [comment]
You have to change back to your root project directory :-)

**Comment by patherk** [comment]
That would do it, clearly wasn't even thinking there :| sorry! 

```
node index.js

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /test/test-api/node_modules/mariasql/build/Release/sqlclient.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/garageverse/gv-mods-api/node_modules/mariasql/lib/Client.js:9:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by mscdex** [comment]
Ok it looks like somehow the addon is being compiled against one "major" node version but ran using another. Is it possible you have multiple versions of node installed somehow (e.g. you had a global installation in say `/usr/local/bin` but you're now using `nvm`)?

**Comment by patherk** [comment]
Okay there is something going on in regards to that, NVM isn't installed, but another node version management thing is installed called N. Think I'll probably just do a fresh install of node LTS and try again. 

Thanks for pointing me in the right direction, hopefully can get this sorted now :)

**Comment by gaastonsr** [comment]
Thanks for the pointer! I had a version of node.js installed and was working fine. Then I updated my node.js and started getting this error.

I just had to remove my node_modules and do a fresh install again.
