### ISSUE TITLE
A error when I used

### ISSUE THREAD

**Issue by arcthur** [mscdex/node-mariasql#15]
hi,
when I execute one sql, mariasql has a error. I don't know the reason.

```shell
/home/admin/node-live/node_modules/mariasql/lib/Client.js:284
      this._client.query(this._curResults._query, this._curResults._useArray);
                   ^
Error: Not ready to query
    at Client._processQueries (/home/admin/node-live/node_modules/mariasql/lib/Client.js:284:20)
    at Client.query (/home/admin/node-live/node_modules/mariasql/lib/Client.js:185:38)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

**Comment by mscdex** [comment]
This should be fixed now in the [rewrite branch](https://github.com/mscdex/node-mariasql/tree/rewrite).
