### ISSUE TITLE
Get error when installing

### ISSUE THREAD

**Issue by dxcqcv** [mscdex/node-mariasql#190]
node version v7.6.0
npm version 5.3.0

the error code
```
 mariasql@0.2.6 install D:\GitCode\auto-activity\node_modules\mariasql
> node-gyp rebuild


D:\GitCode\auto-activity\node_modules\mariasql>if not defined npm_config_node_gyp (node "D:\Users\gaofeng433\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
▒ڴ˽▒▒▒▒▒▒▒▒һ▒▒▒▒▒▒һ▒▒▒▒Ŀ▒▒▒▒Ҫ▒▒▒ò▒▒▒▒▒▒ɣ▒▒▒▒▒ӡ▒/m▒▒▒▒▒ء▒
D:\GitCode\auto-activity\node_modules\mariasql\build\deps\libmariadbclient\libmysql\clientlib.vcxproj(20,3): error MSB4019: δ▒ҵ▒▒▒▒▒▒▒▒Ŀ▒▒D:\Microsoft.Cpp.Default.props▒▒▒▒▒▒ȷ▒▒ <Import> ▒▒▒▒▒е▒·▒▒▒▒ȷ▒▒▒Ҵ▒▒▒▒ϴ▒▒ڸ▒▒ļ▒▒▒
D:\GitCode\auto-activity\node_modules\mariasql\build\deps\libmariadbclient\mysys\mysys.vcxproj(20,3): error MSB4019: δ▒ҵ▒▒▒▒▒▒▒▒Ŀ▒▒D:\Microsoft.Cpp.Default.props▒▒▒▒▒▒ȷ▒▒ <Import> ▒▒▒▒▒е▒·▒▒▒▒ȷ▒▒▒Ҵ▒▒▒▒ϴ▒▒ڸ▒▒ļ▒▒▒
D:\GitCode\auto-activity\node_modules\mariasql\build\deps\libmariadbclient\mysys_ssl\mysys_ssl.vcxproj(20,3): error MSB4019: δ▒ҵ▒▒▒▒▒▒▒▒Ŀ▒▒D:\Microsoft.Cpp.Default.props▒▒▒▒▒▒ȷ▒▒ <Import> ▒▒▒▒▒е▒·▒▒▒▒ȷ▒▒▒Ҵ▒▒▒▒ϴ▒▒ڸ▒▒ļ▒▒▒
D:\GitCode\auto-activity\node_modules\mariasql\build\deps\libmariadbclient\strings\strings.vcxproj(20,3): error MSB4019: δ▒ҵ▒▒▒▒▒▒▒▒Ŀ▒▒D:\Microsoft.Cpp.Default.props▒▒▒▒▒▒ȷ▒▒ <Import> ▒▒▒▒▒е▒·▒▒▒▒ȷ▒▒▒Ҵ▒▒▒▒ϴ▒▒ڸ▒▒ļ▒▒▒
D:\GitCode\auto-activity\node_modules\mariasql\build\deps\libmariadbclient\extra\yassl\taocrypt\taocrypt.vcxproj(20,3): error MSB4019: δ▒ҵ▒▒▒▒▒▒▒▒Ŀ▒▒D:\Microsoft.Cpp.Default.props▒▒▒▒▒▒ȷ▒▒ <Import> ▒▒▒▒▒е▒·▒▒▒▒ȷ▒▒▒Ҵ▒▒▒▒ϴ▒▒ڸ▒▒ļ▒▒▒
D:\GitCode\auto-activity\node_modules\mariasql\build\deps\libmariadbclient\vio\vio.vcxproj(20,3): error MSB4019: δ▒ҵ▒▒▒▒▒▒▒▒Ŀ▒▒D:\Microsoft.Cpp.Default.props▒▒▒▒▒▒ȷ▒▒ <Import> ▒▒▒▒▒е▒·▒▒▒▒ȷ▒▒▒Ҵ▒▒▒▒ϴ▒▒ڸ▒▒ļ▒▒▒
D:\GitCode\auto-activity\node_modules\mariasql\build\deps\libmariadbclient\extra\yassl\yassl.vcxproj(20,3): error MSB4019: δ▒ҵ▒▒▒▒▒▒▒▒Ŀ▒▒D:\Microsoft.Cpp.Default.props▒▒▒▒▒▒ȷ▒▒ <Import> ▒▒▒▒▒е▒·▒▒▒▒ȷ▒▒▒Ҵ▒▒▒▒ϴ▒▒ڸ▒▒ļ▒▒▒
D:\GitCode\auto-activity\node_modules\mariasql\build\deps\libmariadbclient\zlib\zlib.vcxproj(20,3): error MSB4019: δ▒ҵ▒▒▒▒▒▒▒▒Ŀ▒▒D:\Microsoft.Cpp.Default.props▒▒▒▒▒▒ȷ▒▒ <Import> ▒▒▒▒▒е▒·▒▒▒▒ȷ▒▒▒Ҵ▒▒▒▒ϴ▒▒ڸ▒▒ļ▒▒▒
gyp ERR! build error
gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Users\gaofeng433\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Users\\gaofeng433\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\GitCode\auto-activity\node_modules\mariasql
gyp ERR! node -v v7.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mariasql@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mariasql@0.2.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Users\gaofeng433\AppData\Roaming\npm-cache\_logs\2017-09-19T06_39_39_391Z-debug.log

```

**Comment by mscdex** [comment]
There should be more output than that, including the actual error. If this is not pasted directly from the console, then that is where the actual error text should be. Make sure you have the necessary [build environment on Windows](https://github.com/nodejs/node-gyp#on-windows).

**Comment by dxcqcv** [comment]
thanks, solve it with reinstall c++2015

**Comment by roymj88** [comment]
Hi, 

I am having the same issue.

Full log:

```
 git:(master) ✗ npm install mariasql --save

> mariasql@0.2.6 install API/node_modules/mariasql
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `API/node_modules/mariasql/build'
  CXX(target) Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/aes.o
make: g++: Command not found
make: *** [Release/obj.target/taocrypt/deps/libmariadbclient/extra/yassl/taocrypt/src/aes.o] Error 127
make: Leaving directory `API/node_modules/mariasql/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/roy/.nvm/versions/node/v7.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.19.0-80-generic
gyp ERR! command "/home/roy/.nvm/versions/node/v7.0.0/bin/node" "/home/roy/.nvm/versions/node/v7.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd API/node_modules/mariasql
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN tslint@5.7.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev but none was installed.
npm WARN tsutils@2.8.2 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >= 2.4.0-dev || >= 2.5.0-dev || >= 2.6.0-dev || >= 2.7.0-dev but none was installed.
npm ERR! Linux 3.19.0-80-generic
npm ERR! argv "/home/roy/.nvm/versions/node/v7.0.0/bin/node" "/home/roy/.nvm/versions/node/v7.0.0/bin/npm" "install" "mariasql" "--save"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! mariasql@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mariasql@0.2.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mariasql package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mariasql
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mariasql
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     API/npm-debug.log

```

**Comment by mscdex** [comment]
@roymj88 You don't have the necessary build environment installed. See the requirements [here](https://github.com/nodejs/node-gyp#on-unix).
