### ISSUE TITLE
Completey broken on node v11.12.0

### ISSUE THREAD

**Issue by robertdumitrescu** [mscdex/node-mariasql#206]
On node 11, this library is completely broken. Tried several methods, and all are broken.

`
Error: Cannot find module '../build/Debug/sqlclient'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/robert/gitRepos/swp-docker/localpkg-core/node_modules/mariasql/lib/Client.js:13:11)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/robert/gitRepos/swp-docker/localpkg-core/src/queryBuilders/sql.Where.Query.Builder.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/robert/gitRepos/swp-docker/localpkg-core/src/queryBuilders/databaseConnection.Builder.Spec.js:3:28)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /home/robert/gitRepos/swp-docker/BEAUTHS/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/robert/gitRepos/swp-docker/BEAUTHS/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/robert/gitRepos/swp-docker/BEAUTHS/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/home/robert/gitRepos/swp-docker/BEAUTHS/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
`

**Comment by panther7** [comment]
Agree, broken on v12.x too

**Comment by robertdumitrescu** [comment]
I think this module is at EOL. Wouldn't recommend anyone to use it anymore.

**Comment by knoxcard** [comment]
Correct,..use this instead...
https://www.npmjs.com/package/mariadb
