### ISSUE TITLE
client.end() error

### ISSUE THREAD

**Issue by Dexus** [mscdex/node-mariasql#32]
```
Done with all results
Result row: { Database: 'information_schema' }
Result row: { Database: 'mysql' }
Result row: { Database: 'performance_schema' }
Result finished successfully
Done with all results

/root/node_modules/mariasql/lib/Client.js:188
    this._client.end();
                 ^
Error: Already closed
    at Client.destroy (/root/node_modules/mariasql/lib/Client.js:188:18)
    at Client._processQueries (/root/node_modules/mariasql/lib/Client.js:304:12)
    at /root/node_modules/mariasql/lib/Client.js:209:38
    at process._tickCallback (node.js:415:13)
    at process._tickFromSpinner (node.js:390:15)
```

my source:
```
var inspect = require('util').inspect;
var Client = require('mariasql');
var c = new Client();
c.connect({
        host: '127.0.0.1',
        user: 'root',
        password: '12345'
});
c.on('connect', function() {
        console.log('Client connected');
}).on('error', function(err) {
        console.log('Client error: ' + err);
}).on('close', function(hadError) {
        console.log('Client closed');
});
c.query('SHOW DATABASES').on('result', function(res) {
        res.on('row', function(row) {
                console.log('Result row: ' + inspect(row));
        }).on('error', function(err) {
                console.log('Result error: ' + inspect(err));
        }).on('end', function(info) {
                console.log('Result finished successfully');
        });
}).on('end', function() {
        console.log('Done with all results');
});

c.query('SHOW DATABASES').on('result', function(res) {
        res.on('row', function(row) {
                console.log('Result row: ' + inspect(row));
        }).on('error', function(err) {
                console.log('Result error: ' + inspect(err));
        }).on('end', function(info) {
                console.log('Result finished successfully');
        });
}).on('end', function() {
        console.log('Done with all results');
});

c.end(); // throw error
```

**Comment by mscdex** [comment]
This should be fixed in the [rewrite branch](https://github.com/mscdex/node-mariasql/tree/rewrite).
